services:
  - type: web
    name: duolingo-clone-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash startup.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FRONTEND_URL
        value: https://localhost:3000
